//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ResScriptE.rc
//
#define IDS_COLORCODE                   1
#define IDC_SAVEAS                      3
#define IDC_LOAD                        4
#define IDC_DEFAULT                     5
#define IDC_MSX1COLOR                   6
#define IDI_ICON                        101
#define IDR_MENU                        102
#define IDD_VER                         103
#define IDD_SETTING                     104
#define IDD_PROGRESS                    105
#define IDB_LOGO                        106
#define IDR_KEY                         107
#define IDC_SPOIT                       108
#define IDR_MENUSUB                     109
#define IDD_DOTVIEW                     110
#define IDD_SCRIPT                      111
#define IDR_MENUSCRIPT                  112
#define IDI_ICONSCRIPT                  113
#define IDD_DIALOG1                     114
#define IDC_CHGPAL                      115
#define IDD_PLUGIN                      118
#define IDI_HOLD                        119
#define IDI_NOUSE                       120
#define IDC_GOSA                        1001
#define IDC_SC5                         1002
#define IDC_SC7                         1003
#define IDC_SC8                         1004
#define IDC_PAL                         1005
#define IDC_RED                         1006
#define IDC_GREEN                       1007
#define IDC_BLUE                        1008
#define IDC_COL                         1009
#define IDC_MSXRED                      1009
#define IDC_GOSAVAL                     1010
#define IDC_MSXGREEN                    1010
#define IDC_SC12                        1011
#define IDC_MSXBLUE                     1011
#define IDC_INTER                       1012
#define IDC_COLTBL                      1013
#define IDC_NRED                        1014
#define IDC_NGREEN                      1015
#define IDC_NBLUE                       1016
#define IDC_GOSAVALS                    1017
#define IDC_GOSAERR                     1018
#define IDC_GOSAERRS                    1019
#define IDC_FILENAME                    1020
#define IDC_SELCOL                      1020
#define IDC_PROGRESS                    1021
#define IDC_RESIZE                      1021
#define IDC_CMBPLT                      1022
#define IDC_LOADPLT                     1023
#define IDC_CMBSCREEN                   1024
#define IDC_AUTONAME                    1025
#define IDC_CMBALGO                     1026
#define IDC_JKRC                        1027
#define IDC_CMBERR                      1028
#define IDC_PREVIEW                     1029
#define IDC_PALEN                       1030
#define IDC_ENREVS                      1031
#define IDC_SEIDO                       1032
#define IDC_CMBERR2                     1033
#define IDC_CHKZERO                     1034
#define IDC_TILE                        1035
#define IDC_SAVEPLT                     1036
#define IDC_FZCOLOR                     1037
#define IDC_FZERO                       1038
#define IDC_FZ_X                        1039
#define IDC_FZ_Y                        1040
#define IDC_FZC                         1041
#define IDC_COLOR                       1042
#define IDC_192                         1042
#define IDC_COLORCODE                   1043
#define IDC_ZAHYO                       1044
#define IDC_SCRIPT                      1045
#define IDC_MSXCOLOR                    1045
#define IDC_VERSION                     1046
#define IDC_SORT                        1047
#define IDC_CHKDEF                      1048
#define IDC_CMBCNV                      1049
#define IDC_LBLSSET                     1051
#define IDC_PATH                        1052
#define IDC_FOLDER                      1053
#define IDC_COMBO1                      1056
#define IDC_SIZEMODE                    1056
#define IDC_BUTTON1                     1057
#define IDC_FILLC                       1057
#define IDC_RESAMPLE                    1058
#define IDC_FILLCOLOR                   1059
#define IDM_OPEN                        40001
#define IDM_EXIT                        40002
#define IDM_SETTING                     40003
#define IDM_VER                         40004
#define IDM_DEFSET                      40005
#define IDM_NEXT                        40006
#define IDM_PREV                        40007
#define IDM_CLEAR                       40008
#define IDM_SAVE                        40009
#define IDM_REDO                        40010
#define IDM_ALLCLEAR                    40011
#define IDM_NEWDO                       40012
#define IDM_PASTE                       40013
#define IDM_COPY                        40014
#define IDM_SAVEAS                      40015
#define IDM_CHANGE                      40016
#define IDM_DATA                        40017
#define IDM_ORIGNAL                     40018
#define IDM_SPOIT                       40019
#define IDM_SINGLE                      40019
#define IDM_SCRIPT                      40020
#define IDM_RUN                         40023
#define IDM_DOUBLE                      40024
#define IDM_NEW                         40025
#define IDM_ZOOMUP                      40026
#define IDM_ZOOMDOWN                    40027
#define IDM_BMPSAVE                     40028
#define IDM_PLUGIN                      40029
#define IDM_HELP                        40030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
